export default [
  { label: "Not Selected"},  
  { label: "Canadian",value: "canadian" },
  { label: "Cert Clean",value: "certclean"},
  { label: "Chemical Free",value: "chemical free" },
  { label: "Dairy Free",value: "dairy free" },
  { label: "Eco Cert",value: "ewg verified" },
  { label: "Fair Trade",value: "fair trade" },
  { label: "Gluten Free",value: "gluten free" },
  { label: "Hypoallergenic",value: "hypoallergenic" },
  { label: "Natural",value: "natural" },
  { label: "No Talc",value: "No Talc" },
  { label: "Organic",value: "organic" },
  { label: "Peanut Free Product",value: "peanut free product" },
  { label: "Sugar Free",value: "sugar free" },
  { label: "USDA Organic",value: "usda organic" },
  { label: "Vegan",value: "vegan" },
  { label: "Cruelty Free",value: "cruelty free" },
  { label: "Alcohol Free",value: "alcohol free" },
  { label: "Oil Free",value: "oil free" },
  { label: "Purpicks",value: "purpicks" },
  { label: "Slicone Free",value: "silicone free" },
  { label: "Water Free",value: "water free" },
]
